fix: separate element decoding error from verification error
spaceandtimelabs/sxt-proof-of-sql pull request #16
Opened 2024-06-19 16:07 UTC by iajoiner

# Rationale for this change
For arithmetic (such as #14) to work it is necessary to separate element decoding error from verification error. There are already `QueryError::Overflow` and `QueryError::InvalidString` that handle some decoding errors. However currently in practice if overflows do take place we get `VerificationError`. This PR will fix this issue.

# What changes are included in this PR?
- add `QueryError::MiscellaneousDecodingError` to account for decoding errors beyond overflows and invalid strings
- if decoding errors happen we will use them instead of `VerificationError`

# Are these changes tested?
Existing tests do pass.

2024-06-19 16:13 UTC, JayWhite2357 requested changes

2024-06-19 16:13 UTC, JayWhite2357 commented on crates/proof-of-sql/src/sql/proof/provable_query_result.rs
> +    ) -> Option<Result<Vec<S>, QueryError>> {
No reason to have it be both `Result` and `Option`
```suggestion
    ) -> Result<Vec<S>, QueryError> {
```

2024-06-19 18:43 UTC, drcapybara approved these changes
LGTM - not sure if this is a breaking change or not with the switch to Result from Option

2024-06-19 18:46 UTC, iajoiner commented
@drcapybara You are right! It is a breaking change since it changes error messages when certain non-verification errors occur.

2024-06-20 01:12 UTC, JayWhite2357 approved these changes
LGTM

2024-06-20 01:15 UTC, merged