chore: resolve `clippy::doc_markdown` lints in `proof-of-sql`
spaceandtimelabs/sxt-proof-of-sql pull request #214
Opened 2024-10-03 15:58 UTC by mehulmathur16

# Rationale for this change

We have cargo clippy running in our CI in order to enforce code quality. In order to increase our standards, we should enable the clippy::pedantic lint group.

# What changes are included in this PR?

This PR fixes `clippy::doc_markdown` warnings for `proof-of-sql` lib.

# Are these changes tested?

Yes. The following commands should run without any warnings.

- `cargo clippy --lib -p proof-of-sql -- -W clippy::doc_markdown`
- `cargo doc`

2024-10-04 11:36 UTC, mehulmathur16 commented
Hi @JayWhite2357 @iajoiner, can you please review this PR ?

2024-10-04 12:28 UTC, JayWhite2357 requested changes
Few minor changes. Thanks for the attention to detail on this.

2024-10-04 12:28 UTC, JayWhite2357 commented on crates/proof-of-sql/src/base/bit/bit_matrix.rs
> +///   `M_ij = abs(xi) & (1 << bj) == 1`
Can you add ticks around the paragraph above as well to keep this doc uniform?

2024-10-04 12:28 UTC, JayWhite2357 commented on crates/proof-of-sql/src/base/commitment/committable_column.rs
> +    /// Borrowed `SmallInt` column, mapped to `i32`.
```suggestion
    /// Borrowed `Int` column, mapped to `i32`.
```

2024-10-04 12:28 UTC, JayWhite2357 commented on crates/proof-of-sql/src/base/database/column_operation.rs
> +///   - `new_precision` = `left_precision - left_scale + right_scale + new_scale`
NIT:
```suggestion
///   - `new_scale = max(6, right_precision + left_scale + 1)`
///   - `new_precision = left_precision - left_scale + right_scale + new_scale`
```

2024-10-04 12:28 UTC, JayWhite2357 commented on crates/proof-of-sql/src/base/database/owned_and_arrow_conversions.rs
>  //! Decimal75 <-> S
Keep things consistent
```suggestion
//! `1nt128` <-> `Decimal128(38,0)`
//! `Decimal75` <-> `S`
```

2024-10-04 12:28 UTC, JayWhite2357 commented on crates/proof-of-sql/src/base/polynomial/composite_polynomial.rs
> + * See `third_party/license/arkworks.LICENSE`
This shouldn't be a doc comment.
I think this is the correct fix instead:
```rust
/*
 * Adapted from arkworks
 *
 * See third_party/license/arkworks.LICENSE
 */
```

2024-10-04 12:28 UTC, JayWhite2357 commented on crates/proof-of-sql/src/base/polynomial/composite_polynomial.rs
> +/// * Coefficient of ith product `c_i` = `self.products[i].0`
NIT:
```suggestion
/// * Number of multiplicands of `i`th product `m_i = self.products[i].1.len()`,
/// * Coefficient of `i`th product `c_i = self.products[i].0`
```

2024-10-04 12:28 UTC, JayWhite2357 commented on crates/proof-of-sql/src/base/proof/transcript_core.rs
> +/// private method to facilitate recieving challenges and reversing them. Undefined behavior if the `size_of` `M` is not 32 bytes.
NIT:
```suggestion
/// private method to facilitate recieving challenges and reversing them. Undefined behavior if the size of `M` is not 32 bytes.
```

2024-10-04 12:28 UTC, JayWhite2357 commented on crates/proof-of-sql/src/base/slice_ops/batch_inverse.rs
> + * See `third_party/license/arkworks.LICENSE`
As above, this shouldn't be a doc comment.

2024-10-04 13:22 UTC, mehulmathur16 commented on crates/proof-of-sql/README.md
> +Using Proof of SQL, developers can compute over both onchain and offchain datasets in a trustless manner, proving the result back to their smart contract (or offchain verifier) just-in-time during a
@JayWhite2357 Clippy is giving warning to use backticks on DeFi word.

2024-10-04 18:52 UTC, JayWhite2357 commented on crates/proof-of-sql/README.md
> +Using Proof of SQL, developers can compute over both onchain and offchain datasets in a trustless manner, proving the result back to their smart contract (or offchain verifier) just-in-time during a
can you `allow(clippy::doc_markdown)` on just that line? Or just the file?

2024-10-04 19:12 UTC, mehulmathur16 commented on crates/proof-of-sql/README.md
> +Using Proof of SQL, developers can compute over both onchain and offchain datasets in a trustless manner, proving the result back to their smart contract (or offchain verifier) just-in-time during a
I don't think this is achievable in case of Readme file. We can do this for rust docs.

2024-10-04 19:38 UTC, JayWhite2357 commented on crates/proof-of-sql/README.md
> +Using Proof of SQL, developers can compute over both onchain and offchain datasets in a trustless manner, proving the result back to their smart contract (or offchain verifier) just-in-time during a
Hmmm. Take a look at `doc-valid-idents` here: https://rust-lang.github.io/rust-clippy/rust-1.81.0/index.html#/doc_markdown.

2024-10-04 20:15 UTC, mehulmathur16 commented on crates/proof-of-sql/README.md
> +Using Proof of SQL, developers can compute over both onchain and offchain datasets in a trustless manner, proving the result back to their smart contract (or offchain verifier) just-in-time during a
Okay

2024-10-05 01:38 UTC, JayWhite2357 approved these changes

2024-10-05 02:26 UTC, merged