chore: resolve `redundant_closure_for_method_calls` lint warnings
spaceandtimelabs/sxt-proof-of-sql pull request #226
Opened 2024-10-05 18:26 UTC by mehulmathur16

# Rationale for this change

We have cargo clippy running in our CI in order to enforce code quality. In order to increase our standards, we should enable the clippy::pedantic lint group.

# What changes are included in this PR?

Resolved `redundant_closure_for_method_calls` lint warnings

# Are these changes tested?

Yes.

2024-10-06 23:35 UTC, iajoiner commented on crates/proof-of-sql/src/base/commitment/naive_commitment.rs
> +                        u64_vec.iter().map(std::convert::Into::into).collect()
We may as well import `core::convert::Into`. Also please bear in mind that we need to support `no_std` so unless it is absolutely necessary let's not use `std`.

2024-10-06 23:36 UTC, iajoiner commented on crates/proof-of-sql/src/base/database/column.rs
> +                .map(std::string::ToString::to_string)
Similarly `to_string` probably should be imported and `std` should be avoided

2024-10-06 23:36 UTC, iajoiner requested changes
Really thanks for your hard work, @mehulmathur16 !
Please address the comments.

2024-10-07 17:24 UTC, mehulmathur16 commented
Thanks @iajoiner.

2024-10-07 19:36 UTC, JayWhite2357 approved these changes

2024-10-07 19:41 UTC, iajoiner approved these changes
NIT: We really should put `core::convert::Into` etc at the top. I'm fine with this for now though.

2024-10-07 19:47 UTC, JayWhite2357 commented
> NIT: We really should put `core::convert::Into` etc at the top. I'm fine with this for now though.

Agreed. I'm not too opinionated on this though.

2024-10-07 19:52 UTC, merged