refactor:Tidy up scalar module
spaceandtimelabs/sxt-proof-of-sql pull request #255
Opened 2024-10-10 20:21 UTC by winrhcp

Rationale for this change
Mentioned in #234

What changes are included in this PR?
Move the Scalar trait to its own "scalar" file within base/scalar.

/claim #234

2024-10-14 14:14 UTC, stuarttimwhite requested changes
Just one request:
Can you change the file name to just scalar, not scalar_trait?

2024-10-19 03:13 UTC, JayWhite2357 requested changes
Two very small requests on this, and I'll merge.

2024-10-19 03:13 UTC, JayWhite2357 commented on crates/proof-of-sql/src/base/mod.rs
> +/// TODO: add docs
```suggestion
/// This module contains the `Scalar` trait as well as the main, generic, implementations of it.
```

2024-10-19 03:13 UTC, JayWhite2357 commented on crates/proof-of-sql/src/base/scalar/mod.rs
> +pub use super::{encode::VarInt, ref_into::RefInto};
Let's get rid of this.
```suggestion
```

2024-10-19 14:32 UTC, JayWhite2357 approved these changes
Looks good. Thanks!

2024-10-19 19:43 UTC, JayWhite2357 approved these changes

2024-10-19 19:46 UTC, JayWhite2357 commented
/approve

2024-10-19 19:54 UTC, merged