feat: add `SliceExec`
spaceandtimelabs/sxt-proof-of-sql pull request #379
Opened 2024-11-18 23:58 UTC by iajoiner

Please be sure to look over the pull request guidelines here: https://github.com/spaceandtimelabs/sxt-proof-of-sql/blob/main/CONTRIBUTING.md#submit-pr.

# Please go through the following checklist
- [ ] The PR title and commit messages adhere to guidelines here: https://github.com/spaceandtimelabs/sxt-proof-of-sql/blob/main/CONTRIBUTING.md. In particular `!` is used if and only if at least one breaking change has been introduced.
- [ ] I have run the ci check script with `source scripts/run_ci_checks.sh`.

# Rationale for this change

# What changes are included in this PR?

# Are these changes tested?

2024-12-03 21:48 UTC, JayWhite2357 requested changes

2024-12-03 21:51 UTC, JayWhite2357 commented
For my reference: the review was over https://github.com/spaceandtimelabs/sxt-proof-of-sql/commit/86abb7c074f94c7af21c78d1b0af5bcade4cad6c.

2024-12-03 21:56 UTC, iajoiner commented on crates/proof-of-sql/src/sql/proof_plans/slice_exec_test.rs
Sure. In this case we need to error out though due to the comment you made above.

2024-12-03 22:43 UTC, iajoiner commented on crates/proof-of-sql/src/sql/proof_plans/slice_exec.rs
> +    }
This is neat. Thanks!

2024-12-03 22:44 UTC, iajoiner commented on crates/proof-of-sql/src/sql/proof_plans/slice_exec.rs
> +    pub(super) fetch: Option<usize>,
I think the issue here is the ordering. `LIMIT` corresponds to `fetch` and `OFFSET` corresponds to `skip`.

2024-12-04 12:04 UTC, JayWhite2357 submitted a review, later dismissed
FYI: I rebased after #404.
Approved.
I turned of auto-merge so you can address the NITs before merging.

2024-12-04 13:39 UTC, JayWhite2357 approved these changes

2024-12-04 13:40 UTC, iajoiner commented on crates/proof-of-sql/src/sql/proof_plans/mod.rs
> +pub(super) use filter_exec::FilterExec;
Sorry that was a mistake

2024-12-04 14:00 UTC, merged