refactor!: identifier to ident and update docs
spaceandtimelabs/sxt-proof-of-sql pull request #441
Opened 2024-12-17 18:59 UTC by varshith257

Please be sure to look over the pull request guidelines here: https://github.com/spaceandtimelabs/sxt-proof-of-sql/blob/main/CONTRIBUTING.md#submit-pr.

# Please go through the following checklist
- [ ] The PR title and commit messages adhere to guidelines here: https://github.com/spaceandtimelabs/sxt-proof-of-sql/blob/main/CONTRIBUTING.md. In particular `!` is used if and only if at least one breaking change has been introduced.
- [ ] I have run the ci check script with `source scripts/run_ci_checks.sh`.

# Rationale for this change

To update docs to reflect the migration of Identifier -> Ident

# What changes are included in this PR?

- Updated docs in the proof-of-sql crate with Ident

# Are these changes tested?

Part of  #235

2024-12-17 19:00 UTC, iajoiner commented on crates/proof-of-sql/README.md
> +Query result: OwnedTable { table: {Ident { name: "b" }: VarChar(["hello", "world"])} }
@varshith257 Please do run this example and put the results here. I don't think this is simply a string replacement here.

2024-12-17 19:01 UTC, iajoiner commented on crates/proof-of-sql/examples/hello_world/README.md
> +Query result: OwnedTable { table: {Ident { name: "b" }: VarChar(["hello", "world"])} }
Same

2024-12-17 19:03 UTC, iajoiner commented on crates/proof-of-sql/src/base/database/owned_table_utility.rs
> +/// - Panics if `name.parse()` fails to convert the name into an `Ident`.
This shouldn't panic any more. Also we can't run `name.parse()` any more either. Same for other cases.

2024-12-17 19:04 UTC, iajoiner commented on crates/proof-of-sql/src/base/database/table_utility.rs
> +/// Creates an [`Table`] from a list of `(Ident, Column)` pairs.
What I mentioned about `owned_table_utility.rs` applies here as well.

2024-12-17 19:08 UTC, iajoiner reviewed
Really thanks for your PR!
General comments:
1. You don't need to remove the word "identifier" when it refers to the general concept of identifiers rather than `proof_of_sql_parser::Identifier`
2. .The comments on the two table util files need to be fixed in the entire files rather than in just the two instances I mentioned.

2024-12-17 19:12 UTC, iajoiner commented on crates/proof-of-sql/benches/scaffold/random_util.rs
> +/// - The provided identifier cannot be parsed into an `Ident` type.
Yes

2024-12-17 19:46 UTC, iajoiner commented on crates/proof-of-sql/examples/hello_world/README.md
> +Query result: OwnedTable { table: {Ident { name: "b" }: VarChar(["hello", "world"])} }
@varshith257 Well then please use this here and in the other example with such comments as well.

2024-12-17 20:01 UTC, iajoiner approved these changes

2024-12-17 20:03 UTC, iajoiner requested changes
Please remove unnecessary panic docs from `owned_table_utility.rs` and `table_utility.rs`

2024-12-17 20:20 UTC, iajoiner commented
@varshith257 Which issues?

2024-12-18 06:37 UTC, iajoiner approved these changes
Thanks again for the PR!

2024-12-18 15:00 UTC, JayWhite2357 approved these changes

2024-12-18 15:40 UTC, merged